# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/conf.py

formats: [htmlzip]

python:
   install:
   - requirements: docs/sphinx/requirements.txt

build:
   os: ubuntu-22.04
   tools:
      python: "3.10"
   apt_packages:
     - "doxygen"
   jobs:
      post_build:
         - cp safe-vendor/jquery.js    $READTHEDOCS_OUTPUT/html/doxygen/html/jquery.js
         - cp safe-vendor/jquery-ui.js $READTHEDOCS_OUTPUT/html/doxygen/html/jquery-ui.js
         - cp safe-vendor/jquery-ui.css $READTHEDOCS_OUTPUT/html/doxygen/html/jquery-ui.css
