#!/bin/sh

# Simple script to run docker container with GUI resources

XSOCK=/tmp/.X11-unix
XAUTH=/home/$USER/.Xauthority
SHARED_DIR=/home/boat/shared_dir
HOST_DIR=/home/$USER/shared_dir

echo "Shared directory: ${HOST_DIR}"

docker run \
    -it --rm \
    --volume=$XSOCK:$XSOCK:rw \
    --volume=$XAUTH:$XAUTH:rw \
    --volume=$HOST_DIR:$SHARED_DIR:rw \
    --env="XAUTHORITY=${XAUTH}" \
    --env="DISPLAY=${DISPLAY}" \
    -u boat \
    --privileged -v /dev/bus/usb:/dev/bus/usb \
    --net=host \
    --device=/dev/kfd \
    --device=/dev/dri \
    --group-add video \
    mivisionx_rgbdslamv2
